services:
  - type: web
    name: lavangam-backend
    env: python
    plan: free
    buildCommand: |
      echo "🚀 Starting Lavangam Backend build..."
      cd backend
      python -m pip install --upgrade pip
      python -m pip install --upgrade wheel setuptools
      python -m pip install -r requirements-render.txt --no-cache-dir
      echo "✅ Build completed"
    startCommand: |
      echo "🚀 Starting Lavangam Multi-Port Backend..."
      cd backend
      python render_multi_port.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: RENDER_ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: DB_HOST
        value: 44.244.61.85
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: Toolinformation
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: thanuja
      - key: FILE_MANAGER_PORT
        value: 5002
      - key: EPROC_SERVER_PORT
        value: 5023
      - key: SYSTEM_USAGE_PORT
        value: 5024
      - key: DASHBOARD_API_PORT
        value: 8004
      - key: SCRAPERS_API_PORT
        value: 5022
      - key: ANALYTICS_API_PORT
        value: 8001
      - key: ADDITIONAL_ANALYTICS_PORT
        value: 8002
      - key: EPROC_WEBSOCKET_PORT
        value: 5020
      - key: EPROC_API_PORT
        value: 5021
    healthCheckPath: /ping
    autoDeploy: true
