services:
  # Main backend service (already working)
  - type: web
    name: lavangam-backend
    env: python
    buildCommand: pip install -r requirements-ultra-simple.txt
    startCommand: python backend/render_scripts/start_main-backend.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85

  # Eproc Server - Port 5022
  - type: web
    name: lavangam-backend-eproc
    env: python
    buildCommand: pip install -r requirements-ultra-simple.txt
    startCommand: python backend/render_scripts/start_eproc_server.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5022

  # System Usage API - Port 5024
  - type: web
    name: lavangam-backend-system
    env: python
    buildCommand: pip install -r requirements-ultra-simple.txt
    startCommand: python backend/render_scripts/start_system_usage_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5024

  # Dashboard API - Port 8004
  - type: web
    name: lavangam-backend-dashboard
    env: python
    buildCommand: pip install -r requirements-ultra-simple.txt
    startCommand: python backend/render_scripts/start_dashboard_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8004

  # File Manager - Port 5026
  - type: web
    name: lavangam-backend-files
    env: python
    buildCommand: pip install -r requirements-ultra-simple.txt
    startCommand: python backend/render_scripts/start_file_manager.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5026

  # Scraper WebSocket - Port 5028
  - type: web
    name: lavangam-backend-scraper
    env: python
    buildCommand: pip install -r requirements-ultra-simple.txt
    startCommand: python backend/render_scripts/start_scraper_ws.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5028

  # Admin Metrics API - Port 5030
  - type: web
    name: lavangam-backend-metrics
    env: python
    buildCommand: pip install -r requirements-ultra-simple.txt
    startCommand: python backend/render_scripts/start_admin_metrics_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5030

  # Dashboard WebSocket - Port 5032
  - type: web
    name: lavangam-backend-websocket
    env: python
    buildCommand: pip install -r requirements-ultra-simple.txt
    startCommand: python backend/render_scripts/start_dashboard_websocket.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5032
