# Render deployment configuration for Lavangam backend services
# Repository: https://github.com/Mahi-7801/render-frontend
# UPDATED: Fixed all buildCommand paths to use backend/requirements-render.txt
# This ensures all services can find the requirements file correctly

services:
  # Main backend service - Port 8000
  - type: web
    name: lavangam-backend
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_main-backend.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8000

  # Service 1 - Port 8001
  - type: web
    name: lavangam-backend-eproc
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_eproc_server.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8001

  # Service 2 - Port 8002
  - type: web
    name: lavangam-backend-system
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_system_usage_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8002

  # Service 3 - Port 8003 (MISSING PORT ADDED)
  - type: web
    name: lavangam-backend-8003
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_8003_service.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8003

  # Service 4 - Port 8004
  - type: web
    name: lavangam-backend-dashboard
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_dashboard_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8004

  # Service 5 - Port 5002
  - type: web
    name: lavangam-backend-metrics
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_admin_metrics_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5002

  # Service 6 - Port 5003
  - type: web
    name: lavangam-backend-scraper
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_scraper_ws.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5003

  # Service 7 - Port 5021
  - type: web
    name: lavangam-backend-5021
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_system_usage_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5021

  # Service 8 - Port 5022
  - type: web
    name: lavangam-backend-websocket
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_dashboard_websocket.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5022

  # Service 9 - Port 5023
  - type: web
    name: lavangam-backend-5023
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_eproc_server.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5023

  # Service 10 - Port 5024
  - type: web
    name: lavangam-backend-files
    env: python
    repo: https://github.com/Mahi-7801/render-frontend
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r backend/requirements-render.txt --force-reinstall --no-cache-dir
    startCommand: python backend/render_scripts/start_file_manager.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5024
