services:
  # Main backend service - Port 8000
  - type: web
    name: lavangam-backend
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_main-backend.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8000

  # Service 1 - Port 8001
  - type: web
    name: lavangam-backend-8001
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_eproc_server.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8001

  # Service 2 - Port 8002
  - type: web
    name: lavangam-backend-8002
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_system_usage_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8002

  # Service 3 - Port 8004
  - type: web
    name: lavangam-backend-8004
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_dashboard_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 8004

  # Service 4 - Port 5024
  - type: web
    name: lavangam-backend-5024
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_file_manager.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5024

  # Service 5 - Port 5003
  - type: web
    name: lavangam-backend-5003
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_scraper_ws.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5003

  # Service 6 - Port 5002
  - type: web
    name: lavangam-backend-5002
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_admin_metrics_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5002

  # Service 7 - Port 5022
  - type: web
    name: lavangam-backend-5022
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_dashboard_websocket.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5022

  # Service 8 - Port 5023
  - type: web
    name: lavangam-backend-5023
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_eproc_server.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5023

  # Service 9 - Port 5021
  - type: web
    name: lavangam-backend-5021
    env: python
    buildCommand: pip install -r requirements-minimal-working.txt
    startCommand: python backend/render_scripts/start_system_usage_api.py
    envVars:
      - key: RENDER_ENVIRONMENT
        value: production
      - key: DB_HOST
        value: 44.244.61.85
      - key: PORT
        value: 5021
