services:
  - type: web
    name: lavangam-backend
    env: python
    plan: free
    buildCommand: |
      echo "🚀 Starting Lavangam Backend build..."
      cd backend
      python -m pip install --upgrade pip
      python -m pip install --upgrade wheel setuptools
      python -m pip install -r requirements-render.txt --no-cache-dir
      python -c "import fastapi, uvicorn; print('✅ Core packages verified')"
      echo "✅ Build completed"
    startCommand: |
      echo "🚀 Starting Lavangam Consolidated Backend..."
      cd backend
      echo "📁 Current directory: $(pwd)"
      echo "📁 Contents: $(ls -la)"
      echo "🐍 Python version: $(python --version)"
      echo "📦 Installed packages: $(pip list | head -10)"
      echo "🚀 Starting consolidated backend with all services..."
      python render_consolidated.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: RENDER_ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: DB_HOST
        value: 44.244.61.85
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: Toolinformation
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: thanuja  # ⚠️ Consider setting this in Render UI
      - key: FILE_MANAGER_PORT
        value: 5002
      - key: EPROC_SERVER_PORT
        value: 5023
      - key: SYSTEM_USAGE_PORT
        value: 5024
      - key: DASHBOARD_API_PORT
        value: 8004
      - key: SCRAPERS_API_PORT
        value: 5022
      - key: ANALYTICS_API_PORT
        value: 8001
      - key: ADDITIONAL_ANALYTICS_PORT
        value: 8002
      - key: EPROC_WEBSOCKET_PORT
        value: 5020
      - key: EPROC_API_PORT
        value: 5021
      - key: SUPABASE_URL
        value: https://zjfjaezztfydiryzfd.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZmphZXp6dGZ5ZGlyeXpzeXZkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTAyNzAyMSwiZXhwIjoyMDY2NjAzMDIxfQ.sRbGz6wbBoMmY8Ol3vEPc4VOh2oEWpcONi9DkUsTpKk
    healthCheckPath: /health
    autoDeploy: true
