services:
  - type: web
    name: lavangam-backend
    env: python
    plan: free
    buildCommand: |
      echo "🚀 Starting Lavangam Backend build..."
      cd backend
      python -m pip install --upgrade pip
      python -m pip install --upgrade wheel setuptools
      python -m pip install -r requirements-render.txt --no-cache-dir
      echo "✅ Build completed"
    startCommand: |
      echo "🚀 Starting Lavangam Backend..."
      cd backend
      python deploy_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: RENDER_ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /ping
    autoDeploy: true
